# Generated by Django 5.0.14 on 2026-01-23 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freelancerprofile',
            name='bio',
            field=models.TextField(blank=True, default='', help_text='Tell clients about yourself', max_length=2000),
        ),
        migrations.AlterField(
            model_name='freelancerprofile',
            name='title',
            field=models.CharField(blank=True, default='', help_text='Professional title, e.g. "Full Stack Developer"', max_length=100),
        ),
    ]
