# Generated by Django 5.0.14 on 2026-05-02 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_freelancerprofile_bio_and_more'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancerprofile',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Primary work category', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='freelancers', to='projects.category'),
        ),
    ]
